/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.PropertiesDao;
import dao.SalesDao;
import dao.UsersDao;
import javax.swing.JOptionPane;
import model.Properties;
import model.Sales;

/**
 *
 * @author hp
 */
public class SellForm extends javax.swing.JFrame {
   
    AllProperties all = new AllProperties();
    /**
     * Creates new form SellForm
     */
    public SellForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productIdLabel = new javax.swing.JLabel();
        productNameLabel = new javax.swing.JLabel();
        product_id = new javax.swing.JTextField();
        product_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        product_category = new javax.swing.JComboBox<>();
        pro = new javax.swing.JLabel();
        selling_price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        product_type = new javax.swing.JComboBox<>();
        confirmBtn = new javax.swing.JButton();
        doneBtn = new javax.swing.JButton();
        quantityLabel = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        company_id = new javax.swing.JLabel();
        company_name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        profit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Please fill this form to record Selled Property(ies)");

        productIdLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productIdLabel.setText("Property Id:");

        productNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productNameLabel.setText("Property name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Property Category:");

        product_category.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        product_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movable", "Immovable", " " }));
        product_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_categoryActionPerformed(evt);
            }
        });

        pro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pro.setText("Net Profit:");

        selling_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                selling_priceKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Property Type:");

        product_type.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        product_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Other" }));

        confirmBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        doneBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        doneBtn.setText("Done");
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        quantityLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantityLabel.setText("Quantity:");

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityKeyTyped(evt);
            }
        });

        company_id.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        company_id.setText("comp id");

        company_name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        company_name.setText("comp name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Selling Price:");

        profit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                profitKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(productNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(product_name, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(quantityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(confirmBtn)
                        .addGap(33, 33, 33)
                        .addComponent(doneBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(pro, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selling_price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(product_type, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(product_category, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(productIdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(product_id, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(company_id)
                .addGap(32, 32, 32)
                .addComponent(company_name)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(company_id)
                    .addComponent(company_name))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productIdLabel)
                    .addComponent(product_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(product_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(product_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(selling_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(profit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBtn)
                    .addComponent(doneBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void product_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_categoryActionPerformed
        // TODO add your handling code here:
        if(product_category.getSelectedItem().equals("Immovable")){
            product_type.setSelectedItem(null);
            product_type.removeAllItems();
            product_type.addItem("House");
            product_type.addItem("Land");
            product_type.addItem("Forest");
        }
        else{
            product_type.removeAllItems();
            product_type.addItem("Other");
            product_type.setEditable(false);
        }
    }//GEN-LAST:event_product_categoryActionPerformed

    private void selling_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_selling_priceKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!Character.isDigit(character)){
            evt.consume();
        }
    }//GEN-LAST:event_selling_priceKeyTyped

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        if(product_id.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Product Id Required!!");
        }
        else if(product_name.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Product name required!");
        }
        else if(product_category.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "Product category required!");
        }
        else if(product_type.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "Product Type required!");
        }
        else if(quantity.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Quantity required!");
        }
        else if(selling_price.getText()==null){
            JOptionPane.showMessageDialog(this, "Buying Price required!");
        }
        else if(Integer.parseInt(quantity.getText())<=0){
            JOptionPane.showMessageDialog(this, "Quantity can't be zero or negative!");
        }
        else if(Integer.parseInt(selling_price.getText())<=0){
            JOptionPane.showMessageDialog(this, "Buying Price Can't be zero! or negative");
        }
        else{
            Properties property = new Properties();
            SalesDao dao =new SalesDao();
            PropertiesDao prodao = new PropertiesDao();
            
            property.setProperty_id(product_id.getText().trim());
            property.setProperty_name(product_name.getText());
            property.setProperty_category(product_category.getSelectedItem().toString());
            property.setProperty_type(product_type.getSelectedItem().toString());
            property.setAvailable_quantity(Integer.parseInt(quantity.getText()));
            property.setUser_id(Integer.parseInt(company_id.getText().trim()));
            
            UsersDao user = new UsersDao();
            Sales sale= new Sales();
            sale.setProperty_id(product_id.getText().trim());
            sale.setProperty_name(product_name.getText());
            sale.setProperty_category(product_category.getSelectedItem().toString());
            sale.setProperty_type(product_type.getSelectedItem().toString());
           // sale.setAvailable_quantity(Integer.parseInt(quantity.getText()));
            sale.setTotal_quantity(Integer.parseInt(quantity.getText()));
            sale.setSelling_price(Integer.parseInt(selling_price.getText()));
            //Integer profit = Integer.parseInt(selling_price.getText())*15/100;
            sale.setProfit(Integer.parseInt(profit.getText()));
            sale.setUser_id(Integer.parseInt(company_id.getText().trim()));
            if(user.Exists(Integer.parseInt(company_id.getText().trim()))){
                if(prodao.existing(property)){
                    if(dao.exists(sale)){
                        String feedback="";
                     if( prodao.decrementQty(property)){                     
                      feedback = dao.incrementQty(sale);
                      JOptionPane.showMessageDialog(this, feedback,"Action performed",JOptionPane.INFORMATION_MESSAGE);
                     }
                     else{
                       feedback="Property selling failled!!";  
                      JOptionPane.showMessageDialog(this, feedback,"Action performed",JOptionPane.INFORMATION_MESSAGE);
                     }
                    }
                    else{
                    String feedback ="";
                      if(prodao.decrementQty(property)){
                          feedback = dao.addSales(sale);
                         JOptionPane.showMessageDialog(this, feedback,"Action performed",JOptionPane.INFORMATION_MESSAGE);
                      }
                      else{
                          feedback="Property selling failled!!";  
                          JOptionPane.showMessageDialog(this, feedback,"Action performed",JOptionPane.INFORMATION_MESSAGE);
                      }
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this,"Property not found","Error" ,JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"User Does'nt Exists","Error" ,JOptionPane.ERROR_MESSAGE);
            }}
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        // TODO add your handling code here:
        all.company_id.setText(company_id.getText());
        all.company_name.setText(company_name.getText());
        all.addTableColumnsHeaderName();
        all.addTableRowsData(Integer.parseInt(company_id.getText()));
        all.setVisible(true);
        dispose();
    }//GEN-LAST:event_doneBtnActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_quantityActionPerformed

    private void quantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!Character.isDigit(character)){
            evt.consume();
        }
    }//GEN-LAST:event_quantityKeyTyped

    private void profitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_profitKeyTyped
        // TODO add your handling code here:
         char character = evt.getKeyChar();
        if(!Character.isDigit(character)){
            evt.consume();
        }
    }//GEN-LAST:event_profitKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel company_id;
    public javax.swing.JLabel company_name;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JButton doneBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel pro;
    private javax.swing.JLabel productIdLabel;
    private javax.swing.JLabel productNameLabel;
    public javax.swing.JComboBox<String> product_category;
    public javax.swing.JTextField product_id;
    public javax.swing.JTextField product_name;
    public javax.swing.JComboBox<String> product_type;
    public javax.swing.JTextField profit;
    public javax.swing.JTextField quantity;
    private javax.swing.JLabel quantityLabel;
    public javax.swing.JTextField selling_price;
    // End of variables declaration//GEN-END:variables
}
