/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.PropertiesDao;
import dao.UsersDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Properties;

/**
 *
 * @author hp
 */
public class updateForm extends javax.swing.JFrame {

    AllProperties all = new AllProperties();
    DefaultTableModel tableModel = new DefaultTableModel();
    /**
     * Creates new form updateForm
     */
    public updateForm() {
        initComponents();
    }
    
      private void addTableColumnsHeaderName(){
        tableModel.addColumn("Property Id");
        tableModel.addColumn("Property Name");
        tableModel.addColumn("Property Category");
        tableModel.addColumn("Property type");
        tableModel.addColumn("Buying Price");
        tableModel.addColumn("Available Quantity");
        tableModel.addColumn("Rented Quantity");
        tableModel.addColumn("Total Quantity");
        all.myTable.setModel(tableModel);
    }
    
    private void addTableRowsData(Integer id){
        tableModel.setRowCount(0);
        PropertiesDao dao = new PropertiesDao();
        List<Properties> property = dao.allProperties(id);
        for(Properties properties : property)
            tableModel.addRow(new Object[]{
                properties.getProperty_id(),
                properties.getProperty_name(),
                properties.getProperty_category(),
                properties.getProperty_type(),
                properties.getBuying_price(),
                properties.getAvailable_quantity(),
                properties.getRent_quantity(),
                properties.getTotal_quantity(),  
            });
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        productIdLabel = new javax.swing.JLabel();
        productNameLabel = new javax.swing.JLabel();
        property_id = new javax.swing.JTextField();
        property_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        property_category = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        buying_price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        property_type = new javax.swing.JComboBox<>();
        updateBtn = new javax.swing.JButton();
        doneBtn = new javax.swing.JButton();
        quantityLabel = new javax.swing.JLabel();
        rented_quantity = new javax.swing.JTextField();
        company_id = new javax.swing.JLabel();
        company_name = new javax.swing.JLabel();
        quantityLabel1 = new javax.swing.JLabel();
        available_quantity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ProMaSy Update Property(ies) Form");

        productIdLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productIdLabel.setText("Property Id:");

        productNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productNameLabel.setText("Property name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Property Category:");

        property_category.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        property_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movable", "Immovable", " " }));
        property_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                property_categoryActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Buying Price:");

        buying_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buying_priceKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Property Type:");

        property_type.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        property_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Other" }));

        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        doneBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        doneBtn.setText("Done");
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        quantityLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantityLabel.setText("Available Quantity:");

        rented_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rented_quantityActionPerformed(evt);
            }
        });
        rented_quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rented_quantityKeyTyped(evt);
            }
        });

        company_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        company_id.setText("Comp id");

        company_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        company_name.setText("comp name");

        quantityLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantityLabel1.setText("Rented Quantity:");

        available_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                available_quantityActionPerformed(evt);
            }
        });
        available_quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                available_quantityKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityLabel)
                    .addComponent(jLabel5)
                    .addComponent(productIdLabel)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(productNameLabel)
                    .addComponent(quantityLabel1))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(property_name, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buying_price)
                        .addComponent(property_category, 0, 194, Short.MAX_VALUE)
                        .addComponent(property_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rented_quantity)
                        .addComponent(available_quantity))
                    .addComponent(property_id, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(company_id)
                .addGap(26, 26, 26)
                .addComponent(company_name)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(updateBtn)
                .addGap(53, 53, 53)
                .addComponent(doneBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(company_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(company_name))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productIdLabel)
                    .addComponent(property_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(property_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productNameLabel))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(property_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(property_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(quantityLabel)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(available_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLabel1)
                    .addComponent(rented_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(buying_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(doneBtn))
                .addGap(151, 151, 151))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void property_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_property_categoryActionPerformed
        // TODO add your handling code here:
        if(property_category.getSelectedItem().equals("Immovable")){
            property_type.setSelectedItem(null);
            property_type.removeAllItems();
            property_type.addItem("House");
            property_type.addItem("Land");
            property_type.addItem("Forest");
        }
        else{
            property_type.removeAllItems();
            property_type.addItem("Other");
            property_type.setEditable(false);
        }
    }//GEN-LAST:event_property_categoryActionPerformed

    private void buying_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buying_priceKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!Character.isDigit(character)){
            evt.consume();
        }
    }//GEN-LAST:event_buying_priceKeyTyped

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if(property_id.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Product Id Required!!");
        }
        else if(property_name.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Product name required!");
        }
        else if(property_category.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "Product category required!");
        }
        else if(property_type.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "Product Type required!");
        }
        else if(available_quantity.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Quantity required!");
        }
        else if(Integer.parseInt(available_quantity.getText())<=0){
            JOptionPane.showMessageDialog(this, "Quantity can't be zero or negative!");
        }
        else if(rented_quantity.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Quantity required!");
        }
        else if(Integer.parseInt(rented_quantity.getText())<=0){
            JOptionPane.showMessageDialog(this, "Quantity can't be zero or negative!");
        }
        else if(buying_price.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Buying Price required!");
        }
        else if(Integer.parseInt(buying_price.getText())<=0){
            JOptionPane.showMessageDialog(this, "Buying Price can't be zero or negative!");
        }
        else{
            Properties property = new Properties();
            PropertiesDao dao =new PropertiesDao();
            UsersDao user = new UsersDao();
            property.setProperty_id(property_id.getText().trim());
            property.setProperty_name(property_name.getText());
            property.setProperty_category(property_category.getSelectedItem().toString());
            property.setProperty_type(property_type.getSelectedItem().toString());
            property.setAvailable_quantity(Integer.parseInt(available_quantity.getText()));
            property.setRent_quantity(Integer.parseInt(rented_quantity.getText()));
            Integer total = Integer.parseInt(available_quantity.getText())+Integer.parseInt(rented_quantity.getText());
            property.setTotal_quantity(total);
            property.setBuying_price(Integer.parseInt(buying_price.getText()));
            property.setUser_id(Integer.parseInt(company_id.getText().trim()));
            if(user.Exists(Integer.parseInt(company_id.getText().trim()))){
                if(dao.existing(property)){
                    int feedback = dao.update(property);
                    if(feedback>0)
                       JOptionPane.showMessageDialog(this, "Property Updated Successfully!","Congratulations",JOptionPane.INFORMATION_MESSAGE);
                    else
                        JOptionPane.showMessageDialog(this,"Sorry, Property Update failled!","Ooops" ,JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Sorry, Property doesn't Exist!","Ooops" ,JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"User Does'nt Exists","Error" ,JOptionPane.ERROR_MESSAGE);
            }}
    }//GEN-LAST:event_updateBtnActionPerformed

    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        // TODO add your handling code here:
        all.company_id.setText(company_id.getText());
        all.company_name.setText(company_name.getText());
        addTableColumnsHeaderName();
        addTableRowsData(Integer.parseInt(company_id.getText()));
        all.setVisible(true);
        dispose();
    }//GEN-LAST:event_doneBtnActionPerformed

    private void rented_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rented_quantityActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rented_quantityActionPerformed

    private void rented_quantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rented_quantityKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!Character.isDigit(character)){
            evt.consume();
        }
    }//GEN-LAST:event_rented_quantityKeyTyped

    private void available_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_available_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_available_quantityActionPerformed

    private void available_quantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_available_quantityKeyTyped
        // TODO add your handling code here:
         char character = evt.getKeyChar();
        if(!Character.isDigit(character)){
            evt.consume();
        }
    }//GEN-LAST:event_available_quantityKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField available_quantity;
    public javax.swing.JTextField buying_price;
    public javax.swing.JLabel company_id;
    public javax.swing.JLabel company_name;
    private javax.swing.JButton doneBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel productIdLabel;
    private javax.swing.JLabel productNameLabel;
    public javax.swing.JComboBox<String> property_category;
    public javax.swing.JTextField property_id;
    public javax.swing.JTextField property_name;
    public javax.swing.JComboBox<String> property_type;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel quantityLabel1;
    public javax.swing.JTextField rented_quantity;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
